### ISSUE TITLE
Feature request: Razor IMU firmware support

### ISSUE THREAD

**Issue by r57zone** [infinitellamas/Arduino-Tracker-Plugin#3]
Can you create another plugin for the popular firmware Razor AHRS (Arduino + GY-85)?
Messages on serial port:
#YPR=136.05,42.97,-8.17
(yaw, pitch, roll)

It would be nice to add a reset button (probably CTRL + Shift + R) and the ability to replace the axis, for example, arduino_serial_yaw to osvr_pitch (and other axes).

Thanks.

**Comment by terminal29** [comment]
Is there an example script for the Razor AHRS ? I think it would be easier to modify that script to suit the plugin rather than making a whole new plugin for each different script. If you or anyone seeing this is interested in making a script for your own MPU device, the Arduino->PC protocol is as follows:

``D:<insert message here>`` // Used for descriptors, basically just information that will be forwarded to the osvr console

``C:[begin/end]`` // Internally the same as descriptors, and are sent at the beginning and end of the calibration procedure

``Q:####,####,####,####`` // Quaternion data format W,X,Y,Z with any amount of decimal places supported

``E:<insert message here>`` // Same as a descriptor but is used for displaying errors. (Looking now I actually forgot to handle this in the plugin)

Then the PC->Arduino protocol goes like this:

``C`` // Used to tell the arduino we want to calibrate the MPU.

Note: The arduino establishes a serial connection and starts sending quaternion data as soon as it can. There is no Request-Response system as I found it to increase the already long lag time.

**Comment by r57zone** [comment]
Ok, thanks.
